Moesif/moesif-dotnet

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/MoesifMiddleware.cs

Add: SamplingPercentage option
Bump version to 0.1.1

Add: SamplingPercentage option

---

Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/MoesifMiddleware.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Add: Dynamically configure sampling events
Update Dependencies
Bump version to 0.1.2

Add: Dynamically configure sampling events

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/Properties/AssemblyInfo.cs

Fix: Update Dependency version
Bump version to 0.1.3

Fix: Update Dependency version

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/MoesifMiddleware.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Refactor: Update dependencies
Bump version to 0.1.4

Refactor: Update dependencies

---

Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/MoesifMiddleware.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Fix: Package Reference
Fix: Send Response to client
Bump version to 0.1.5

Fix: Package Reference

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/MoesifMiddleware.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Add: Transaction Id to Request-Response Headers
Bump version to 0.1.6

Add: Transaction Id to Request-Response Headers

---

Moesif.Middleware.Test/Moesif.Middleware.Test.csproj
Moesif.Middleware.Test/MoesifMiddlewareTest.cs
Moesif.Middleware.sln
Moesif.Middleware/Helpers/ClientIp.cs
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/MoesifMiddleware.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
README.md

Add: Unit Test
Add: updateUser function
Add: Support for proxy server where we could not get the ip address
Update: READMe.md
Bump version to 0.1.7

Add: Unit Test

---

Moesif.Middleware.Test/MoesifMiddlewareTest.cs
Moesif.Middleware/Helpers/CompanyHelper.cs
Moesif.Middleware/Helpers/MoesifCaptureOutgoingRequestHandler.cs
Moesif.Middleware/Helpers/UserHelper.cs
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/MoesifMiddleware.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
README.md

Add: Update company and batch companies functions
Add: Capture Outgoing API calls
Add: Test to capture outgoing api calls
Update: README.md
Bump version to 0.2.0

Add: Update company and batch companies functions

---

Moesif.Middleware.Test/MoesifMiddlewareTest.cs
Moesif.Middleware/Helpers/MoesifCaptureOutgoingRequestHandler.cs
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/MoesifMiddleware.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
README.md

Add: CompanyId to the EventModel
Refactor: Test to capture CompanyId
Update: README.md
Bump version to 0.2.1

Add: CompanyId to the EventModel

---

Moesif.Middleware.Test/MoesifMiddlewareTest.cs
Moesif.Middleware/Helpers/MoesifCaptureOutgoingRequestHandler.cs
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/MoesifMiddleware.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
README.md

Add: LogBody configuration option to remove request and response body
Add: Configuration option in the test
Update: README.md
Bump version to 0.2.2

Add: LogBody configuration option to remove request and response body

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Refactor: Support reading request body for Asp NetCore3
Fix: Issue #16
Bump version to 1.0.3

Refactor: Support reading request body for Asp NetCore3

---

Moesif.Middleware/Helpers/AppConfig.cs
Moesif.Middleware/Helpers/Tasks.cs
Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
README.md

Add: Support for sending events in batch
Add: Support for sampling events by user and company
Bump version to 1.1.0
Update: README.md

Add: Support for sending events in batch

---

Moesif.Middleware/Helpers/MoesifCaptureOutgoingRequestHandler.cs
Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
Moesif.Middleware/packages.config
Moesif.NetFramework.Test/Moesif.NetFramework.Test.csproj
Moesif.NetFramework.Test/packages.config

Add: direction field to specify incoming or outgoing API call
Bump moesifapi dependency to 1.1.7
Bump version to 1.1.1

Add: direction field to specify incoming or outgoing API call

---

Moesif.Middleware/Helpers/AppConfig.cs
Moesif.Middleware/Helpers/MoesifCaptureOutgoingRequestHandler.cs
Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
Moesif.Middleware/packages.config
Moesif.NetFramework.Test/Moesif.NetFramework.Test.csproj
Moesif.NetFramework.Test/packages.config

Add: User/Company sampling for outgoing events
Add: Weight field to event model
Refactor: Bump Moesif.Api version to 1.1.9
Bump version to 1.1.2

Add: User/Company sampling for outgoing events

---

README.md

Refactor: Update User and Companies section

Refactor: Update User and Companies section

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/MoesifMiddleware.cs
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
Moesif.NetCore.Test/MoesifNetCoreTest.cs
README.md

Add: Middleware class constructor for NetCore Framework
Refactor: NetCore Framework Test
Refactor: Update README.md
Bump version to 1.1.3

Add: Middleware class constructor for NetCore Framework

---

README.md

Fix: Net Framework Instruction

Fix: Net Framework Instruction

---

Moesif.Middleware/Helpers/AppConfig.cs
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetFramework/Helpers/LoggerHelper.cs
Moesif.Middleware/NetFramework/Helpers/StreamHelper.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Refactor: NetFramework middleware to read from MVC and OWIN stream
Add: Support for gzip body
Refactor: Create helper functions
Bump version to 1.1.4

Refactor: NetFramework middleware to read from MVC and OWIN stream

---

.gitignore
LICENSE
Moesif.Middleware/Helpers/AppConfig.cs
Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/MoesifMiddleware.cs
Moesif.Middleware/NetFramework/Helpers/ClientIp.cs
Moesif.Middleware/NetFramework/Helpers/LoggerHelper.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
Moesif.Middleware/packages.config
Moesif.NetFramework.Test/Moesif.NetFramework.Test.csproj
Moesif.NetFramework.Test/packages.config

- Ensure correct deps are installed based on target framework
- Cleanup nuspec and csproj
- Switch to NET45

Fix: Target .NET Framework 4.5, add correct deps

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Fix: Event Weight for net framework
Bump version to 1.1.6

Fix: Event Weight for net framework

---

LICENSE
Moesif.Middleware/Helpers/AppConfig.cs
Moesif.Middleware/Helpers/MoesifCaptureOutgoingRequestHandler.cs
Moesif.Middleware/Helpers/Tasks.cs
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Refactor: Avoid class variable for moesif config option
Refactor: Convert response headers and eTag key to lowercase
Bump version to 1.3.2

Refactor: Avoid class variable for moesif config option

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetFramework/Helpers/LoggerHelper.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Fix: Check for empty contentType
Bump version to 1.3.3

Fix: Check for empty contentType

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Refactor: Enable batching by default
Bump version to 1.3.4

Refactor: Enable batching by default

---

Moesif.Middleware/Helpers/Tasks.cs
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Refactor: Schedule Worker for NetFramework
Add: queueSize Configuration option
Bump version to 1.3.5

Refactor: Schedule Worker for NetFramework

---

Moesif.Middleware/Helpers/UserHelper.cs
Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/Helpers/LoggerHelper.cs
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/Helpers/LoggerHelper.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
README.md

Add: Fetch userId from Authorization Header
Refactor: Schedule Worker for NetCore framework
Refactor: Add Helper functions for NetCore framework
Bump version to 1.3.6

Fetch user from headers

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/Properties/AssemblyInfo.cs

Add: Jwt Dependency to nuspec
Bump version to 1.3.7

Add: Jwt Dependency to nuspec

---

Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
Moesif.NetFramework.Test/Moesif.NetFramework.Test.csproj
Moesif.NetFramework.Test/packages.config

Fix: Initialize batch max time config option
Bump version to 1.3.8

Fix: Initialize batch max time config option

---

Moesif.Middleware/Moesif.Middleware.nuspec

Refactor: Moesif.Api dependency version

Refactor: Moesif.Api dependency version

---

Moesif.Middleware/Helpers/Tasks.cs
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Refactor: Use Concurrent queue
Bump version to 1.3.9

Refactor: Use Concurrent queue

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/Properties/AssemblyInfo.cs

Refactor: Bump version to 1.3.10

Refactor: Bump version to 1.3.10

---

Moesif.Middleware/Helpers/Compression.cs
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/Helpers/LoggerHelper.cs
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/Helpers/LoggerHelper.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Refactor: Read Request Content Async
Refactor: Bump version to 1.3.11

Refactor: Read Request Content Async

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetFramework/Helpers/LoggerHelper.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Add: Config option to reset request body stream for .NET Framework
Bump version to 1.3.13

Add: Config option to reset request body stream for .NET Framework

---

README.md

Refactor: Add troubleshooting section in README.md

Refactor: Add troubleshooting section in README.md

---

Moesif.Middleware/Helpers/AppConfigHelper.cs
Moesif.Middleware/Helpers/GovernanceHelper.cs
Moesif.Middleware/Helpers/LoggingHelper.cs
Moesif.Middleware/Helpers/MoesifCaptureOutgoingRequestHandler.cs
Moesif.Middleware/Helpers/Tasks.cs
Moesif.Middleware/Models/AppConfig.cs
Moesif.Middleware/Models/Governance.cs
Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/Helpers/LoggerHelper.cs
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/Helpers/LoggerHelper.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
Moesif.NetCore.Test/Moesif.NetCore.Test.csproj
Moesif.NetCore.Test/MoesifNetCoreTest.cs
Moesif.NetFramework.Test/Moesif.NetFramework.Test.csproj
Moesif.NetFramework.Test/packages.config

This PR will add governance rule in .NET middleware
#183200518
1. added governance model and helper
2. blocked traffic based on governance rule
3. used volatile instead for concurrency
4. used event notification to reduce API calls
5. convert sync calls to async calls
6. added unit tests for governance rule
7. bumped up version

Governance Support

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

1. reread userId and companyId in the response cycle
2. bump up version

Bugfix: userId is not available in the request cycle

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Bump up version to publish correct build

---

Moesif.Middleware/Helpers/GovernanceHelper.cs
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Extract UserId only if governance rule is defined

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/Properties/AssemblyInfo.cs
Moesif.NetFramework.Test/packages.config

Use latest moesif api SDK 2.0.5

---

Moesif.Middleware/Helpers/GovernanceHelper.cs
Moesif.Middleware/Helpers/Tasks.cs
Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
Moesif.NetCore.Test/Moesif.NetCore.Test.csproj
Moesif.NetFramework.Test/Moesif.NetFramework.Test.csproj
Moesif.NetFramework.Test/packages.config

Update - use latest Moesif API package.

---

Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/Properties/AssemblyInfo.cs
Moesif.NetCore.Test/Moesif.NetCore.Test.csproj
Moesif.NetFramework.Test/Moesif.NetFramework.Test.csproj
Moesif.NetFramework.Test/packages.config

#185465572 : Use latest .Net CSharp SDK 2.0.8

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/MoesifMiddleware.cs
Moesif.Middleware/NetCore/Helpers/LoggerHelper.cs
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/Helpers/LoggerHelper.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
Moesif.NetCore.Test/MoesifNetCoreTest.cs
Moesif.NetFramework.Test/MoesifNetFrameworkTest.cs

#185768865 #185744077 : reodering getUserId, version update

---

Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/MoesifMiddleware.cs
Moesif.Middleware/NetCore/Helpers/LoggerHelper.cs
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/Helpers/LoggerHelper.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Refactor: Skip logging multipart/form-data body
Refactor: Skip logging body if logBody set to false in netframework middleware 
Refactor: Target the netframework to 461
Bump version to 1.4.4

#187631069 Refactor: Skip logging multipart/form-data body

---

Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Fix: System.IdentityModel.Tokens.Jwt dependency version 
Bump version to 1.4.6

Fix: System.IdentityModel.Tokens.Jwt dependency version

---

Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
Moesif.NetFramework.Test/Moesif.NetFramework.Test.csproj
Moesif.NetFramework.Test/app.config
Moesif.NetFramework.Test/packages.config

Refactor: Microsoft.Extensions.Logging to version 3.1.32 
Refactor: System.IdentityModel.Tokens.Jwt to version 6.35.0 
Refactor: NetFramework Test to include correct dependencies 
Bump version to 1.4.8

#187737081 Refactor: Microsoft.Extensions.Logging to version 3.1.32

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
README.md

Add: Support for aws lambda
Refactor: Update README.md 
Bump version to 1.4.9

#188129245 Add: Support for logging body in aws lambda

---

Moesif.Middleware/Helpers/AppConfigHelper.cs
Moesif.Middleware/Helpers/GovernanceHelper.cs
Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/Helpers/LoggerHelper.cs
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

Refactor: Added Instrumentation and perf improve for netCore middleware
Bump version to 1.5.0

#188509201 Refactor: Added Instrumentation and perf improve for netCore middleware

---

Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.NetCore.Test/Moesif.NetCore.Test.csproj
Moesif.NetFramework.Test/Moesif.NetFramework.Test.csproj
Moesif.NetFramework.Test/packages.config

Refactor: Update tests to use latest version of Moesif.Api
Refactor: Update userAgentString to 1.5.0

#188509201  Refactor: Update tests to use latest version of Moesif.Api

---

Moesif.Middleware/Helpers/Compression.cs
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/Helpers/LoggerHelper.cs
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/Helpers/LoggerHelper.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs
README.md

#188545343 : Added support for maxBodySize and fixed logBody

---

Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

```
Passed!  - Failed:     0, Passed:    19, Skipped:     0, Total:    19, Duration: 13 s - [2024-11-22_14:15:52] > 
```

#243026895: Fix the creation of stream only if needed for both Owin and MVC apps.

---

Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs

#243026895: Create Owin Stream only if needed.

---

Moesif.Middleware/Helpers/AppConfigHelper.cs
Moesif.Middleware/Helpers/GovernanceHelper.cs
Moesif.Middleware/Helpers/MoesifCaptureOutgoingRequestHandler.cs
Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/Helpers/LoggerHelper.cs
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

#188509201: Performance Improvement + Cleanup 

---

Moesif.Middleware/Helpers/AppConfigHelper.cs
Moesif.Middleware/Helpers/GovernanceHelper.cs
Moesif.Middleware/Helpers/Tasks.cs
Moesif.Middleware/Moesif.Middleware.csproj
Moesif.Middleware/Moesif.Middleware.nuspec
Moesif.Middleware/NetCore/Helpers/LoggerHelper.cs
Moesif.Middleware/NetCore/MoesifMiddlewareNetCore.cs
Moesif.Middleware/NetFramework/MoesifMiddlewareNetFramework.cs
Moesif.Middleware/Properties/AssemblyInfo.cs

#188509201 [Part 2 of 3] : Performance improvement
